"""
svg generator service module.
handles svg validation, optimization, and post-processing.
this module works alongside the llm processor to ensure
generated svg code is valid and optimized for rendering.
"""

import logging
import re
from typing import Optional
from xml.etree import ElementTree as ET

logger = logging.getLogger(__name__)


class SVGValidationError(Exception):
    """raised when svg validation fails."""

    pass


class SVGGenerator:
    """
    service for svg validation, optimization, and generation utilities.
    provides methods for cleaning, validating, and enhancing svg code
    generated by the llm processor.
    """

    # default viewbox dimensions used when creating new svgs
    DEFAULT_VIEWBOX = "0 0 400 300"
    DEFAULT_WIDTH = 400
    DEFAULT_HEIGHT = 300

    def __init__(self):
        """initialize the svg generator with default settings."""
        self.svg_namespace = "http://www.w3.org/2000/svg"

    def validate_svg(self, svg_code: str) -> bool:
        """
        validate that the provided string is valid svg.
        performs basic xml parsing and checks for required svg elements.

        args:
            svg_code: svg code string to validate

        returns:
            true if valid, false otherwise
        """
        try:
            # attempt to parse as xml
            root = ET.fromstring(svg_code)

            # check that root element is svg
            tag_name = root.tag.lower()
            if not tag_name.endswith("svg"):
                logger.warning(f"root element is not svg: {tag_name}")
                return False

            return True

        except ET.ParseError as e:
            logger.warning(f"svg xml parsing failed: {e}")
            return False

    def sanitize_svg(self, svg_code: str) -> str:
        """
        sanitize svg code by removing potentially harmful elements.
        removes script tags, event handlers, and external references
        to prevent xss and other security issues.

        args:
            svg_code: svg code to sanitize

        returns:
            sanitized svg code
        """
        # remove script tags and their content
        svg_code = re.sub(
            r"<script[\s\S]*?</script>", "", svg_code, flags=re.IGNORECASE
        )

        # remove on* event handlers (onclick, onload, etc.)
        svg_code = re.sub(r'\s+on\w+\s*=\s*["\'][^"\']*["\']', "", svg_code)

        # remove javascript: urls
        svg_code = re.sub(
            r'(href|xlink:href)\s*=\s*["\']javascript:[^"\']*["\']',
            "",
            svg_code,
            flags=re.IGNORECASE,
        )

        # remove external entity references
        svg_code = re.sub(r"<!ENTITY[^>]*>", "", svg_code)

        return svg_code

    def optimize_svg(self, svg_code: str) -> str:
        """
        optimize svg code for smaller file size and better performance.
        removes unnecessary whitespace and comments while preserving structure.

        args:
            svg_code: svg code to optimize

        returns:
            optimized svg code
        """
        # remove xml comments (but keep svg comments for debugging)
        # we keep comments that might be useful for understanding the visualization

        # collapse multiple whitespace into single space
        svg_code = re.sub(r"\s+", " ", svg_code)

        # remove whitespace between tags
        svg_code = re.sub(r">\s+<", "><", svg_code)

        # trim leading and trailing whitespace
        svg_code = svg_code.strip()

        return svg_code

    def add_viewbox(self, svg_code: str, viewbox: Optional[str] = None) -> str:
        """
        ensure the svg has a viewbox attribute.
        adds a default viewbox if one is not present.

        args:
            svg_code: svg code to modify
            viewbox: optional custom viewbox value

        returns:
            svg code with viewbox attribute
        """
        viewbox = viewbox or self.DEFAULT_VIEWBOX

        # check if viewbox already exists
        if re.search(r'viewBox\s*=', svg_code, re.IGNORECASE):
            return svg_code

        # add viewbox to the opening svg tag
        svg_code = re.sub(
            r"<svg",
            f'<svg viewBox="{viewbox}"',
            svg_code,
            count=1,
            flags=re.IGNORECASE,
        )

        return svg_code

    def add_responsive_attributes(self, svg_code: str) -> str:
        """
        add attributes to make the svg responsive.
        sets width and height to 100% so the svg scales with its container.

        args:
            svg_code: svg code to modify

        returns:
            svg code with responsive attributes
        """
        # remove fixed width and height if present
        svg_code = re.sub(r'\s+width\s*=\s*["\'][^"\']*["\']', "", svg_code)
        svg_code = re.sub(r'\s+height\s*=\s*["\'][^"\']*["\']', "", svg_code)

        # add responsive width and height
        svg_code = re.sub(
            r"<svg",
            '<svg width="100%" height="100%"',
            svg_code,
            count=1,
            flags=re.IGNORECASE,
        )

        return svg_code

    def process_svg(
        self,
        svg_code: str,
        sanitize: bool = True,
        optimize: bool = False,
        responsive: bool = True,
    ) -> str:
        """
        apply a pipeline of processing steps to svg code.
        combines sanitization, optimization, and responsive attributes.

        args:
            svg_code: svg code to process
            sanitize: whether to sanitize for security
            optimize: whether to optimize for size
            responsive: whether to add responsive attributes

        returns:
            processed svg code
        """
        if sanitize:
            svg_code = self.sanitize_svg(svg_code)

        svg_code = self.add_viewbox(svg_code)

        if responsive:
            svg_code = self.add_responsive_attributes(svg_code)

        if optimize:
            svg_code = self.optimize_svg(svg_code)

        return svg_code

    def create_placeholder_svg(
        self, message: str = "loading visualization..."
    ) -> str:
        """
        create a placeholder svg to display while content is loading.
        shows a loading animation or message.

        args:
            message: text to display in the placeholder

        returns:
            placeholder svg code
        """
        escaped_message = message.replace("<", "&lt;").replace(">", "&gt;")

        return f"""<svg viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
  <!-- placeholder svg shown during loading -->
  <rect width="400" height="300" fill="#f8f9fa"/>

  <!-- loading animation circles -->
  <g transform="translate(200, 130)">
    <circle cx="-30" cy="0" r="8" fill="#6c757d">
      <animate attributeName="opacity" values="1;0.3;1" dur="1s" repeatCount="indefinite" begin="0s"/>
    </circle>
    <circle cx="0" cy="0" r="8" fill="#6c757d">
      <animate attributeName="opacity" values="1;0.3;1" dur="1s" repeatCount="indefinite" begin="0.2s"/>
    </circle>
    <circle cx="30" cy="0" r="8" fill="#6c757d">
      <animate attributeName="opacity" values="1;0.3;1" dur="1s" repeatCount="indefinite" begin="0.4s"/>
    </circle>
  </g>

  <!-- loading message -->
  <text x="200" y="180" text-anchor="middle" font-family="system-ui" font-size="14" fill="#6c757d">
    {escaped_message}
  </text>
</svg>"""

    def create_error_svg(self, error_message: str) -> str:
        """
        create an svg that displays an error message.
        used when svg generation fails.

        args:
            error_message: error text to display

        returns:
            error svg code
        """
        escaped_error = error_message[:100].replace("<", "&lt;").replace(">", "&gt;")

        return f"""<svg viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
  <!-- error state svg -->
  <rect width="400" height="300" fill="#fff5f5" stroke="#fed7d7" stroke-width="2"/>

  <!-- error icon -->
  <g transform="translate(200, 100)">
    <circle cx="0" cy="0" r="30" fill="none" stroke="#e53e3e" stroke-width="3"/>
    <line x1="0" y1="-15" x2="0" y2="5" stroke="#e53e3e" stroke-width="3" stroke-linecap="round"/>
    <circle cx="0" cy="15" r="3" fill="#e53e3e"/>
  </g>

  <!-- error message -->
  <text x="200" y="170" text-anchor="middle" font-family="system-ui" font-size="16" fill="#c53030" font-weight="bold">
    generation failed
  </text>
  <text x="200" y="195" text-anchor="middle" font-family="system-ui" font-size="12" fill="#742a2a">
    {escaped_error}
  </text>
</svg>"""

    def wrap_svg_for_animation(self, svg_code: str, animation_type: str = "fade") -> str:
        """
        wrap svg code with animation effects for smoother transitions.
        adds css animations to the svg element.

        args:
            svg_code: svg code to wrap
            animation_type: type of animation (fade, scale, slide)

        returns:
            svg code with animation styles
        """
        animation_styles = {
            "fade": """
    <style>
      @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
      svg { animation: fadeIn 0.5s ease-in-out; }
    </style>""",
            "scale": """
    <style>
      @keyframes scaleIn { from { transform: scale(0.9); opacity: 0; } to { transform: scale(1); opacity: 1; } }
      svg { animation: scaleIn 0.3s ease-out; }
    </style>""",
            "slide": """
    <style>
      @keyframes slideIn { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
      svg { animation: slideIn 0.4s ease-out; }
    </style>""",
        }

        style = animation_styles.get(animation_type, animation_styles["fade"])

        # insert style after opening svg tag
        svg_code = re.sub(
            r"(<svg[^>]*>)",
            f"\\1{style}",
            svg_code,
            count=1,
            flags=re.IGNORECASE,
        )

        return svg_code
